name: SynD
channels:
  - defaults
dependencies:
  - python=3.8.12
  - numpy=1.21.0
  - pandas=1.4.2
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - shap=0.40.0
  - xgboost=1.6.1
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.0
  - pip:
    - biopython==1.79
    - multiprocess==0.70.13
    - primer3-py==0.6.1